import React from 'react';
import { View, Text, StyleSheet, FlatList, Image, TouchableOpacity } from 'react-native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';
import { RootStackParamList } from '../types.ts';

type ListItem = {
  id: string;
  title: string;
  description: string;
  image?: string;
  autogenerated: boolean;
};

const lists: ListItem[] = [
  { id: '1', title: 'Ver más tarde', description: 'Lista autogenerada', autogenerated: true },
  { id: '2', title: 'Favoritos', description: 'Lista autogenerada', autogenerated: true },
  { id: '3', title: 'Películas ya vistas', description: 'Lista autogenerada', autogenerated: true },
  { 
    id: '4', 
    title: 'Calma mi corazón', 
    description: 'Cada que veo estas películas me siento en paz.', 
    image: 'https://images.cdn3.buscalibre.com/fit-in/360x360/11/1f/111f3d03cbd764957d8d5e701b91dfe2.jpg',
    autogenerated: false 
  },
];

const MisListasScreen = () => {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();

  const renderItem = ({ item }: { item: ListItem }) => (
    <TouchableOpacity style={styles.item}>
      {item.image && <Image source={{ uri: item.image }} style={styles.image} />}
      <View style={styles.textContainer}>
        <Text style={styles.title}>{item.title}</Text>
        <Text style={styles.description}>{item.description}</Text>
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Mis listas</Text>
      </View>
      <FlatList
        data={lists}
        keyExtractor={(item) => item.id}
        renderItem={renderItem}
        ItemSeparatorComponent={() => <View style={styles.separator} />}
      />
      <TouchableOpacity
        style={styles.newButton}
        onPress={() => navigation.navigate('NuevaLista')}
      >
        <Text style={styles.newButtonText}>+ Nuevo</Text>
      </TouchableOpacity>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#01161E',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  header: {
    alignItems: 'center',
    marginBottom: 16,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  image: {
    width: 50,
    height: 75,
    marginRight: 12,
    borderRadius: 4,
  },
  textContainer: {
    flex: 1,
  },
  title: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  description: {
    color: '#A1A1A1',
    fontSize: 14,
  },
  separator: {
    height: 1,
    backgroundColor: '#124559',
  },
  newButton: {
    backgroundColor: '#EFF6E0',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginVertical: 16,
  },
  newButtonText: {
    color: '#01161E',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default MisListasScreen;
